puts "The students of December 2014 cohort are..."
puts "----------------"
puts "Kieran Goodacre"
puts "The Joker"
puts "Batman"
puts "Spiderman"
puts "Superman"
puts "El Goucho"
puts "Iceman"
puts "Fireman"
